# Generated by Django 3.1.7 on 2021-04-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210419_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='prueba', max_length=50),
            preserve_default=False,
        ),
    ]
